### ISSUE TITLE
FileLoadException: A strongly-named assembly is required.

### ISSUE THREAD

**Issue by petarpetrovt** [thomaslevesque/NString#11]
Exception: 
System.IO.FileLoadException: Could not load file or assembly 'NString, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by thomaslevesque** [comment]
Hi @petarpetrovt,

That's because you're attempting to use NString from a strong-named assembly, which can only reference strong-named assemblies. NString itself isn't strong-named, so it doesn't work. 

For a while, the consensus in the C# OSS community was to *not* strong-name assemblies, so I didn't. However, this seems to have changed; Microsoft now [recommends strong-naming open-source libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming). So I think I will do so at some point, but it won't happen overnight.

In the meantime, you can use https://github.com/brutaldev/StrongNameSigner to strong-name third-party assemblies yourself.

**Comment by thomaslevesque** [comment]
I added a strong name, and since that's a breaking change, I bumped the version to 2.0.0.
